name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Переходим в папку проекта
            cd /home/${{ secrets.SSH_USER }}/shop-app-js-30
            
            # 2. Скачиваем свежий код из репозитория
            git fetch --all
            git reset --hard origin/main
            
            # 3. Обновляем .env файл
            cat <<EOF > .env
            MONGO_DB_URL=mongodb://shop-mongo-db:27017/shop
            URL_CORS=http://${{ secrets.SSH_HOST }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
            CLIENT_ID=${{ secrets.CLIENT_ID }}
            CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}
            EOF
            
            # 4. Принудительная сборка без использования старого кэша
            # Это решит проблему с nginx.conf
            docker compose build --no-cache
            
            # 5. Перезапуск контейнеров
            docker compose up -d